### ISSUE TITLE
Attack params for I-inf

### ISSUE THREAD

**Issue by iamgroot42** [MadryLab/robustness#11]
What were the attack parameters used for evaluating the models made available, when running PGD with the L-inf norm? I tried evaluating a normal model (no adversarial training) against the PGD attack wit L-inf norm, eps = 0.03 (~8/255), and attack-lr set to 0.1, and I got ~40% accuracy on perturned examples, while the table says it was close to zero. What am I doing wrong?

**Comment by dtsip** [comment]
It looks like the attack-lr is too high. You are taking steps of size 0.1 when you are constraining each pixel to only change by 0.03.

As stated in the README, we use a PGD attack with 20 steps, norm='inf', and attack-lr=2.5 * eps / steps, which would translate to 2.5 * 0.03 / 20 = 0.00375 for this case.

**Comment by iamgroot42** [comment]
My bad, I skipped over that part of the README 😅 Thanks!
