### ISSUE TITLE
SLIDE attack?

### ISSUE THREAD

**Issue by iamgroot42** [MadryLab/robustness#12]
I've written a basic implementation for the [SLIDE](https://arxiv.org/pdf/1904.13000.pdf) variant (modified L-1 PGD), and I think it may be useful to have it included it in this package. Should I go ahead and submit a PR for it?

**Comment by dtsip** [comment]
Thank you for the suggestion!

So, based on my understanding, it is not entirely clear that this is the "best" L1-based attack for training or testing robust models. For instance Croce and Hein, 2019 (https://arxiv.org/abs/1907.02044) report that EAD (https://arxiv.org/abs/1709.04114) performs better on most datasets and models.

In general, we would rather wait until further research converges to a "canonical" L1-based attack before including it in our library.
