### ISSUE TITLE
adversarial training does not seem to learn using command line tool

### ISSUE THREAD

**Issue by khieu** [MadryLab/robustness#19]
I have tried using the adversarial training command line tool to train a robust cifar 10 classifier as well as an external dataset (CalTech101). After 5 iteration, the network stops learning and the evaluation accuracy for natural images is only 10% (50% for accuracy 5 which i assume is top 5 accurate).
In the paper Towards Deep Learning Models Resistant to Adversarial
Attacks https://arxiv.org/pdf/1706.06083.pdf , i see a claim for accuracy of 45 to around 80% across multiple type of attacks, is the claim in the paper top 5 accuracy ?

Also, this is my command for training cifar 10: 
`python -m robustness.main --dataset cifar --data    $PATH-CIFAR10 --adv-train 1 --arch resnet50    --out-dir $CIFAR10-ROBUST --eps 3.0 --attack-lr 0.5 --constraint 2`
and for external dataset Caltech 101:
`python -m robustness.main --dataset CalTech101 --data $PATH-CALTECH101 --adv-train 1 --arch resnet50 --out-dir $CALTECH-ROBUST --attack-steps 30 --constraint inf --eps 3.0 --attack-lr 0.1 --use-best 1 `

Thank you so much for any suggestion and help!

**Comment by lengstrom** [comment]
I think your `eps` might be too high for the algorithm to learn -- what happens when you set it to `0.5`?

**Comment by andrewilyas** [comment]
As @lengstrom mentioned, your epsilon for CIFAR is probably much too high (around 0.5 is reasonable).

For CalTech101, please note that the pixels are scaled to [0, 1], so an L_infinity bound of 3.0 means that the whole image can change (which is probably why the classifier can't learn). An L_infinity bound of 0.05 and an attack_lr of 0.01 is probably more reasonable.

**Comment by khieu** [comment]
thank you for the suggestion! I think the performance is better now. I used --eps 3.0 because the example in the documentation used that value (but for image net dataset).
