### ISSUE TITLE
Python version compatibility f-strings

### ISSUE THREAD

**Issue by j-cb** [MadryLab/robustness#20]
The files datasets.py and loaders.py (pip installation on Python 3.5) both contain an f-string, which produces a syntax error since it is a Python 3.6+ feature. After editing the two lines in the package files, it seems to work fine for me. 
If the package is meant to be compatible with Python 3.5, this should be changed.

**Comment by andrewilyas** [comment]
Thanks for alerting us to this---the library is indeed not compatible with Python 3.5. We'll make a note of this in the README.
