### ISSUE TITLE
Cuda Issues with Input Manipulation with Custom Model

### ISSUE THREAD

**Issue by chsanford** [MadryLab/robustness#21]
I'm currently following along with [the notebook for input manipulation](https://github.com/MadryLab/robustness/blob/master/notebooks/Input%20manipulation%20with%20pre-trained%20models.ipynb), with the exception that I'm using a model that I trained locally.  I run into a several cuda-related issues when I follow the recommended steps for generating adversarial examples. I am using a GPU for training.

I import my saved model as follows:
```
arch = 'resnet18'
ds = CIFAR('../data/cifar/')
classifier_model = ds.get_model(arch, False) if \
                            isinstance(arch, str) else arch
model = AttackerModel(classifier_model, ds)
model.load_state_dict(ch.load(model_path))
```

When, I run the below code to return adversarial examples, I get the following error.
```
kwargs = {
    'constraint':'2',
    'eps': ATTACK_EPS,
    'step_size': ATTACK_STEPSIZE,
    'iterations': ATTACK_STEPS,
    'targeted': True,
    'do_tqdm': True
}
_, im_adv = model(im, targ, make_adv=True, **kwargs)
```
<details>
  <summary>RuntimeError: expected device cpu but got device cuda:0
</summary>
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-b0b53520de12> in <module>
      1 # Finds adversarial examples
----> 2 _, im_adv = model(im, targ, make_adv=True, **kwargs)

~/adversarial/adverarial-env/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

~/adversarial/adverarial-env/lib/python3.7/site-packages/robustness/attacker.py in forward(self, inp, target, make_adv, with_latent, fake_relu, no_relu, with_image, **attacker_kwargs)
    303             prev_training = bool(self.training)
    304             self.eval()
--> 305             adv = self.attacker(inp, target, **attacker_kwargs)
    306             if prev_training:
    307                 self.train()

~/adversarial/adverarial-env/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

~/adversarial/adverarial-env/lib/python3.7/site-packages/robustness/attacker.py in forward(self, x, target, constraint, eps, step_size, iterations, random_start, random_restarts, do_tqdm, targeted, custom_loss, should_normalize, orig_input, use_best, return_image, est_grad, *_)
    239             adv_ret = to_ret
    240         else:
--> 241             adv_ret = get_adv_examples(x)
    242 
    243         return adv_ret

~/adversarial/adverarial-env/lib/python3.7/site-packages/robustness/attacker.py in get_adv_examples(x)
    206 
    207                     x = step.step(x, grad)
--> 208                     x = step.project(x)
    209                     if do_tqdm: iterator.set_description("Current loss: {l}".format(l=loss))
    210 

~/adversarial/adverarial-env/lib/python3.7/site-packages/robustness/attack_steps.py in project(self, x)
    116         """
    117         """
--> 118         diff = x - self.orig_input
    119         diff = diff.renorm(p=2, dim=0, maxnorm=self.eps)
    120         return ch.clamp(self.orig_input + diff, 0, 1)

RuntimeError: expected device cpu but got device cuda:0
</details>

Otherwise, the rest of the code is as implemented in the notebook.

I also tried the following modifications to that line, which reversed the expected device error:
```
_, im_adv = model(im.cuda(), targ, make_adv=True, **kwargs)
```
<details>
<summary>
RuntimeError: expected device cuda:0 but got device cpu
</summary>
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-16-b6e9634fd569> in <module>
      1 # Finds adversarial examples
----> 2 _, im_adv = model(im.cuda(), targ, make_adv=True, **kwargs)

~/adversarial/adverarial-env/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

~/adversarial/adverarial-env/lib/python3.7/site-packages/robustness/attacker.py in forward(self, inp, target, make_adv, with_latent, fake_relu, no_relu, with_image, **attacker_kwargs)
    303             prev_training = bool(self.training)
    304             self.eval()
--> 305             adv = self.attacker(inp, target, **attacker_kwargs)
    306             if prev_training:
    307                 self.train()

~/adversarial/adverarial-env/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

~/adversarial/adverarial-env/lib/python3.7/site-packages/robustness/attacker.py in forward(self, x, target, constraint, eps, step_size, iterations, random_start, random_restarts, do_tqdm, targeted, custom_loss, should_normalize, orig_input, use_best, return_image, est_grad, *_)
    239             adv_ret = to_ret
    240         else:
--> 241             adv_ret = get_adv_examples(x)
    242 
    243         return adv_ret

~/adversarial/adverarial-env/lib/python3.7/site-packages/robustness/attacker.py in get_adv_examples(x)
    186             for _ in iterator:
    187                 x = x.clone().detach().requires_grad_(True)
--> 188                 losses, out = calc_loss(step.to_image(x), target)
    189                 assert losses.shape[0] == x.shape[0], \
    190                         'Shape of losses must match input!'

~/adversarial/adverarial-env/lib/python3.7/site-packages/robustness/attacker.py in calc_loss(inp, target)
    150             '''
    151             if should_normalize:
--> 152                 inp = self.normalize(inp)
    153             output = self.model(inp)
    154             if custom_loss:

~/adversarial/adverarial-env/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

~/adversarial/adverarial-env/lib/python3.7/site-packages/robustness/tools/helpers.py in forward(self, x)
    116     def forward(self, x):
    117         x = ch.clamp(x, 0, 1)
--> 118         x_normalized = (x - self.new_mean)/self.new_std
    119         return x_normalized
    120 

RuntimeError: expected device cuda:0 but got device cpu
</details>

Running this modified version returned the same error:
```
_, im_adv = model(im.cuda(), targ.cuda(), make_adv=True, **kwargs)
```

Do you have any advice on how to resolve this issue? I haven't been able to find many similar problems online among Pytorch users.

**Comment by andrewilyas** [comment]
Hi! I'm not 100% sure what the issue is, but I've seen related stuff happen in PyTorch so I can try to help. Can you start by trying to add the following command:

```python
model = ch.nn.DataParallel(model)
```

and pasting the traceback if there is still an error?

**Comment by chsanford** [comment]
That seems to work! Thank you so much for helping out!!

**Comment by andrewilyas** [comment]
No worries!
