### ISSUE TITLE
Attribute Error: Can't get attribute '__main__' on <module 'builtins' (built-in)>

### ISSUE THREAD

**Issue by nmudur** [MadryLab/robustness#22]
I can't seem to be able to load the pre-trained models CIFAR10 models. While the model corresponding to Eps=0.0 (standard training) loads, I get an error message stating AttributeError: Can't get attribute '__main__' on <module 'builtins' (built-in)> with the non-zero epsilon models. I tried importing the ResNet and resnet50 classes, since other sources on the internet seem to indicate that this might have to do with the pickle.load() function requiring the explicit class definition but that did not work either. I'd be grateful for any directions on this.

```
import torch
from torchvision.models import resnet50

if torch.cuda.is_available():
    device='gpu'
else:
    device='cpu'

mod_nat=torch.load('trained_models_cifar/cifar_nat.pt', map_location=device) #Works
mod_eps_01=torch.load('trained_models_cifar/cifar_l2_1_0.pt', map_location=device) #Error
```
```
Traceback (most recent call last):
  File "/home/nayantara/anaconda2/envs/py3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-a37045f836d2>", line 12, in <module>
    mod_eps_01=torch.load('trained_models_cifar/cifar_l2_1_0.pt', map_location=device)
  File "/home/nayantara/anaconda2/envs/py3/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/nayantara/anaconda2/envs/py3/lib/python3.7/site-packages/torch/serialization.py", line 613, in _load
    result = unpickler.load()
AttributeError: Can't get attribute '__main__' on <module 'builtins' (built-in)>

```

**Comment by andrewilyas** [comment]
To resume models, we would recommend using the ``model_utils.make_and_restore_model`` function, as in the documentation (robustness.readthedocs.io):
```python
from robustness import model_utils, datasets
PATH = # whatever is written in here

ds = datasets.CIFAR("/tmp")
m, _ = model_utils.make_and_restore_model(arch="resnet50", dataset=ds, resume_path=PATH)
```

Alternatively, you can adjust your code by doing ``import dill``, and then adding the ``pickle_module=dill`` argument into ch.load.

Let me know if this doesn't fix the issue!

**Comment by nmudur** [comment]
Thanks a lot! The `import dill` solution worked (I don't have a gpu on the system I'm working on and was thus attempting to load the models without the robustness package). I was also wondering where I could find documentation for the parameters stored in the dictionary of both models? I did find the `robustness.train.train_model` but I was curious because I noticed that the standard training cifar10 model (cifar_nat.pt) has more fields than the robust training model (cifar_l2_1_0.pt), and was wondering why I'm seeing this difference.

**Comment by andrewilyas** [comment]
I think it's just saved with an earlier version of the library :) the keys in ``robustness.train.train_model`` are the current ones.

**Comment by andrewilyas** [comment]
Closing this issue now, let me know if something else arises!

**Comment by yeklou** [comment]
AttributeError: Can't get attribute 'Model' on <module '__main__' from 'C:\\Users\\eklou\\repos\\DataSets\\app-Deployment_flask.py'>
when I tried to import dill package, I am getting ModuleNotFoundError: No module named 'dill'. Please, help
Thanks!
