### ISSUE TITLE
Hyperparameters for adversarial training.

### ISSUE THREAD

**Issue by phibenz** [MadryLab/robustness#25]
Hello, thanks for the awesome repo. 
I am currently replicating your results. 
Could you please share the hyperparameter settings for adversarial training?
Currently, I am assuming the following: 

CIFAR10 L2-norm (ResNet50):
Epsilon: as specified (0.25, 0.5, 1.0)
Step_size: Epsilon/5
Iterations: 7
Random start: False

CIFAR10 Linf-norm (ResNet50):
Epsilon: as specified (8/255)
Step_size: 0.01
Iterations: 7
Random start: False

ImageNet L2-norm (ResNet50):
Epsilon: as specified (3.0)
Step_size: Epsilon/5
Iterations: 7
Random start: False

ImageNet Linf-norm (ResNet50):
Epsilon: as specified (4/255, 8/255)
Step_size: 0.01
Iterations: 7
Random start: False

Are these correct? 
Thanks and all the best

**Comment by andrewilyas** [comment]
These all look reasonable! We've found that adversarial training is pretty consistent over choices of reasonable hyperparameters.

**Comment by lsmaerz** [comment]
I am currently using the package for my master's thesis. It would really help me to know which adversaries were used during training. Specifically, the number steps, step length, as well as the types of randomizations and restarts that got used.
Thanks alot!
