### ISSUE TITLE
ImageNet pre-trained model

### ISSUE THREAD

**Issue by iamgroot42** [MadryLab/robustness#26]
Do you have a code snippet to convert the pre-trained ImageNet model to be compatible with the model class in the Robustness package? Or perhaps the model itself, if you used it in your experiments post-conversion?

**Comment by iamgroot42** [comment]
From what I understand, a resnet50(pretrained=True) call should suffice. Although, I noticed that this pretrained model is half the size of the pre-trained adversarially robust models made available via the repository (imagenet_linf_4, imagenet_l2_3_0). Is there any particular reason behind that?

**Comment by dtsip** [comment]
Yes, `resnet50(pretrained=True)` should suffice. I am not sure I follow your question about model size?

**Comment by iamgroot42** [comment]
The pre-trained L-inf and L-2 models available in the README are 196MB each. However, if I load `resnet50(pretrained=True)` and then save it (using `save_checkpoint`), it's actually only 98MB. Is there any specific reason for that?

**Comment by iamgroot42** [comment]
It seems that this is because the AttackModel is not added by default. I've tried the following snippet to get a robustness compatible version of the vanilla Resnet50 Imagenet classifier.

```
model_kwargs = {
	'arch': 'resnet50',
	'dataset': ds,
	'pytorch_pretrained': True
}
model, _ = make_and_restore_model(**model_kwargs)
sd_info = {
	'model': model.state_dict(),
	'epoch': 1
}
save_checkpoint(sd_info, False, model_path)
```

However, trying to use the saved model for anything yields an error : somehow it seems parts of the prefix of the keys are removed while saving? For instance, "model.layer3.2.bn2.running_var" becomes "ayer3.2.bn2.running_var"

**Comment by iamgroot42** [comment]
Figured it out : While parsing the checkpoint, the first x characters (corresponding to len("module.") are skipped. This gets added only when a DataParallel wraps the original model, which was somehow not happening when loading the model in the way described above? Added that wrapper before saving the model, and it seems to work just fine. It would be nice if this version of the model could just be uploaded along with the other models, instead of users of the pacakge having to do all of this
