### ISSUE TITLE
Imagenet L-inf Robust Accuracy

### ISSUE THREAD

**Issue by iamgroot42** [MadryLab/robustness#29]
I tested the eps=4 L-inf model on Imagenet. Although the accuracy on unperturbed seeds seems to match the numbers given in the README table, I got only 12.206% top-1 accuracy with attacking with Linf (eps=4/255, iters=20, attack-lr = 2.5 * (4/255) / 20), whereas the README reports 33.58%. Am I missing something?

**Comment by dtsip** [comment]
I run the following command using the eps=4 L-inf model (from [here](https://www.dropbox.com/s/axfuary2w1cnyrg/imagenet_linf_4.pt?dl=0)) and I get 33.57% robust accuracy. Can you try this and let us know what you get?
```
python -m robustness.main --dataset imagenet --data /path/to/imagenet --eval-only 1 \
  --out-dir output --arch resnet50 --adv-eval 1 --eps 0.0156862745  --constraint inf \
  --attack-steps 20 --attack-lr 0.00196078431 --resume imagenet_linf_4.pt
```
