### ISSUE TITLE
Shouldn't this (and related lines) use dim=0? 

### ISSUE THREAD

**Issue by jamieray** [MadryLab/robustness#32]
https://github.com/MadryLab/robustness/blob/ca52df73bb94f5a3abb74d95b82a13589354a83e/robustness/attack_steps.py#L134

**Comment by dtsip** [comment]
You are right, thanks for spotting! Fixed in a733a8815ccfe386dda35bbc12c96b5929d5411b 

This should not affect any of our reported results since we don't use random start for PGD.
