### ISSUE TITLE
Is there a pre-trained model file for restricted ImageNet model (10 classes)?

### ISSUE THREAD

**Issue by ndb796** [MadryLab/robustness#33]
Hi! Thank you for sharing good project :)

Is there a pre-trained model file for the restricted ImageNet model (10 classes)?

I could find only the adversarially trained restricted ImageNet model file.
(https://github.com/MadryLab/robust_representations)

But, I cannot find a naturally trained restricted ImageNet model file.

**Comment by dtsip** [comment]
Hi, I uploaded a pre-trained Restricted ImageNet model [here](https://robustmodels.s3.amazonaws.com/RestrictedImageNetNat.pt) and also linked to it from the [robust representations repo](https://github.com/MadryLab/robust_representations). Hope that helps.

**Comment by ArturoDeza** [comment]
Is there a script to create the Restricted ImageNet folders/dataset from the ImageNet folder?
