### ISSUE TITLE
`AttackerModel` doesn't do normal inference 

### ISSUE THREAD

**Issue by NoahAmsel** [MadryLab/robustness#37]
Hi there,
Great work on this package! Forgive me if I'm missing something, but there seems to be a mismatch between how `AttackerModel.forward` works, and the documentation. I want to call `AttackerModel.forward` and just do normal inference without returning any image. I should be able to do this by setting `make_adv=False` and `with_image=False`. But as I can see [here](https://github.com/MadryLab/robustness/blob/6347646ae47120d35f47220eabd507cebbd6c914/robustness/attacker.py#L322) this just sets the output to `None`! Moreover, it still outputs a tuple with the input image as the second element. 

Finally, the docstring contains a broken link: "see `our detailed
walkthrough <../example_usage/input_space_manipulation>`".

As an addendum, you might consider making the default behavior being to just do normal inference and not attack or output an image. This may make it easier to incorporate an `AttackerModel` object as a step in other modules.
Thanks!
-N

**Comment by NoahAmsel** [comment]
Basically I think output should never be `None`, and when `with_image == False` it should be the only return value rather than being part of a tuple.

**Comment by andrewilyas** [comment]
Thanks for pointing this out, there is definitely a bug somewhere in there (output should indeed never be None haha), and the link should have a ``.ipynb`` at the end probably, will fix both of these soon and update on PyPI. I also like the idea of only returning one value if ``with_image=False``.

**Comment by Hadisalman** [comment]
Fixed. See cec6e4fd283f937d6d28f84e20103f5eb1e0070d.
