### ISSUE TITLE
Initial Weights

### ISSUE THREAD

**Issue by amirrezashaeiri** [MadryLab/robustness#39]
Hi,

Thank you for sharing your pre-trained models!

I am wondering if you can share your initial weights also.

Thank you.

**Comment by andrewilyas** [comment]
Hi!

Unfortunately we don't have a checkpoint from before training for the released models---the training process is pretty robust though so you should get similar results by just training your own model from a new init and saving it (see the docs for a tutorial on how to do this)

**Comment by amirrezashaeiri** [comment]
aha, I see, actually, I want to compute quantities like distance to initialization for the ImageNet models, which need much time to train using standard GPUs!

anyway, thank you.
