### ISSUE TITLE
Transform arg does not passed into the Dataset construction

### ISSUE THREAD

**Issue by LR32768** [MadryLab/robustness#45]
Hi. When I am using your package for getting a RestrictedImageNet dataloader, it seems that the argument of transform_train and transform_test does not affect the output image. Then I read your code and found that the construction does not use the passed-in transform but the default DA.TRANSFORM_TRAIN instead. 
A small issue, but looking forward to fixing them. THX

**Comment by andrewilyas** [comment]
This has been fixed on the ``develop`` branch, which will be merged in sometime this week.

**Comment by andrewilyas** [comment]
This should now be fixed on the master branch!
