### ISSUE TITLE
No ImageNetHierarchy 

### ISSUE THREAD

**Issue by zhmiao** [MadryLab/robustness#58]
Hello! Thanks for the great toolkit. I think the new update removed the ImageNetHierarchy class. Is there anything for replacement? Thanks again.

**Comment by yogeesh-alphaics** [comment]
hi , 
i am also facing the same issue. Please update as soon as possible.

**Comment by ShibaniSanturkar** [comment]
Thanks for pointing this out. Our previous commit accidentally omitted the ImageNetHierarchy class. Should be fixed in #60 which will be merged with master later today.

**Comment by andrewilyas** [comment]
Hi all,

Thanks for bringing up this issue! It's now fixed on the master branch and on PyPI. Feel free to re-open the issue if you encounter other issues!
