### ISSUE TITLE
Datasets?

### ISSUE THREAD

**Issue by iamgroot42** [MadryLab/robustness#6]
This code (along with some other projects using it, such as : https://github.com/MadryLab/robust_representations/blob/master/image_inversion.ipynb) load CIFAR, Imagenet, etc from a directory structure with train/test folders etc. However, I could not find a data link for these datasets in this format. The in-built data loaders for these datasets seem to handle these very differently. Could you please point me to the exact datasets that this library intends to use when loading datasets?

**Comment by andrewilyas** [comment]
CIFAR is set to auto-download, so you can just give it the root directory where you want the data to be downloaded (e.g. `/tmp` or something). 

For the rest of the datasets, they should be downloaded in Pytorch ImageFolder format, i.e. something like this:
```
data_path/
     train/
          class_A/
          class_B/
          class_C/
     test/
          class_A/
          class_B/
          class_C/
```

There should be many resources online for formatting ImageNet into this format, e.g.: https://github.com/facebook/fb.resnet.torch/blob/master/INSTALL.md#download-the-imagenet-dataset
