### ISSUE TITLE
About the std in normalization.

### ISSUE THREAD

**Issue by qimingyudaowenti** [MadryLab/robustness#70]
You use `[0.2023, 0.1994, 0.2010]` as the std constant to perform normalization: 

https://github.com/MadryLab/robustness/blob/a610690a3c9008bd3f096f73163223e8d3582155/robustness/datasets.py#L354

but I get different value:

```
from torchvision import datasets

train_set = datasets.CIFAR10(root='~/torchvision_dataset',
                             train=True, download=False)

print(train_set.data.shape)
print(train_set.data.mean(axis=(0, 1, 2)) / 255)
print(train_set.data.std(axis=(0, 1, 2)) / 255)


# --- output ---
# (50000, 32, 32, 3)
# [0.49139968 0.48215841 0.44653091]
# [0.24703223 0.24348513 0.26158784]
```

So, how are these values (`[0.2023, 0.1994, 0.2010]`) calculated？

**Comment by andrewilyas** [comment]
They were taken from here: https://github.com/kuangliu/pytorch-cifar/blob/master/main.py

I'll look into the values you posted though and see how they compare in terms of performance.

**Comment by andrewilyas** [comment]
Hi! I checked and you are correct, the normalization values are slightly off. This maybe will yield a small performance boost, but on the other hand will require re-training all of our models to make them work with this normalization. While we might revisit this in the future, I don't have the computational resources to do this at the moment.

Thanks for the catch!
