### ISSUE TITLE
Training times for robust models?

### ISSUE THREAD

**Issue by MalharJ** [MadryLab/robustness#76]
Is it possible to get an estimate of how much time it takes to train a robust ImageNet model, like say ResNet-50 for epsilon=4/255?

**Comment by Hadisalman** [comment]
Hi @MalharJ, 

It mainly depends on the number of PGD steps you use, the batch-size, and your GPU. As an example, a robust ImageNet model trained with a 3-step PGD with a batch-size of 512 on 4 V100 GPUs should take ~1.6 hrs/epoch (~6 days for a full 90 epoch training).

Hope this helps!

**Comment by MalharJ** [comment]
Sounds good, thanks!

**Comment by iamsh4shank** [comment]
Hi, I am using this code to adversarilly train the reset_v2 model so I have used the code from robustness library where I am first changing the forward function of the imported model based on what we need according the library. But running it mutliple GPUs returns problem with the devices. Is there any fixed script that we should use to avoid this?
