### ISSUE TITLE
Pre-Trained Model

### ISSUE THREAD

**Issue by sdan2** [MadryLab/robustness#87]
How do I exactly load a pre-trained model? I have the downloaded cifar_linf_8.pt file. Then I do the following:

from robustness.cifar_models.resnet import ResNet50
model=ResNet50()
model.load_state_dict(torch.load("cifar_nat.pt"))

However, I am getting an error saying the keys do not match. Do you have any suggestions on what to do?
Thanks!

**Comment by andrewilyas** [comment]
Yes, see the ``robustness.model_utils.make_and_restore_model`` function, that should help!

**Comment by sdan2** [comment]
Thanks, that worked!
