### ISSUE TITLE
imagenet dataset download

### ISSUE THREAD

**Issue by GaoJiqiang** [MadryLab/robustness#95]
I want to train a standard model on imagenet, but there has a problem when downloading the dataset.

![image](https://user-images.githubusercontent.com/32474257/113375623-62698680-93a2-11eb-8e43-180977cb7d21.png)

**Comment by Hadisalman** [comment]
Hi @GaoJiqiang, you have to first download ImageNet before running the code (the code won't download it automatically for you).

Basically you have to obtain a copy of ImageNet (http://www.image-net.org/index), then preprocess the val directory to look like the train directory by running [this script](https://raw.githubusercontent.com/soumith/imagenetloader.torch/master/valprep.sh). Finally, point `--data` to the directory containing the `train` and `val` folders of ImageNet that you downloaded and processed.

Hope this helps!
